Repository jrkgus413/nb2-dearcarmate-team1, pull requests merged in 2025-07, with the labels that each got.

#35 images/upload 엔드포인트 작업
  .env.example
  .gitignore
  package-lock.json
  package.json
  prisma/models/contract-document.prisma.part
  src/app.ts
  src/controllers/images.controller.ts
  src/handlers/global-error.handler.ts
  src/handlers/not-found.handler.ts
  src/repositories/images.repository.ts
  src/routes/images.router.ts
  src/services/images.service.ts
  src/types/error.type.ts
  src/types/file.type.ts
  src/utils/error.util.ts
  src/utils/firebase.ts
  src/utils/from.util.ts
  src/utils/prisma.util.ts
Labels: 🚀 feat

#52 refactor: 중복 함수 제거 및 전체 코드 스타일 통일
  src/controllers/company.controller.ts
  src/repositories/company.repository.ts
  src/routes/company.router.ts
  src/services/company.service.ts
  src/utils/db.util.ts
Labels: ♻️ refactor, 📝 todo

#66 refactor: Customer 모델 enum 적용
  prisma/models/customer.prisma.part
Labels: ♻️ refactor

#70 feat: 토큰 유틸 추가
  .env.example
  package-lock.json
  package.json
  src/app.ts
  src/enums/cookie.enum.ts
  src/types/express.d.ts
  src/types/payload.type.ts
  src/utils/env.util.ts
  src/utils/firebase.ts
  src/utils/token.util.ts
Labels: 🚀 feat

#76 fix: prisma Customer 스키마 수정
  prisma/models/customer.prisma.part
Labels: 🐛 fix

#77 feat: 고객 API 구현(초기)
  src/controllers/customer.controller.ts
  src/repositories/customer.repository.ts
  src/routes/customer.router.ts
  src/services/customer.service.ts
  src/types/customer.type.ts
Labels: 🚀 feat

#80 feat: 대시보드 기능 API 구현
  prisma/models/car.prisma.part
  src/app.ts
  src/controllers/dashboard.controller.ts
  src/repositories/car.repository.ts
  src/repositories/dashboard.repository.ts
  src/routes/dashboard.router.ts
  src/services/dashboard.service.ts
  src/types/car.type.ts
  src/types/contract.type.ts
  src/types/dashboard.type.ts
  src/utils/parse.util.ts
Labels: 🚀 feat
